name: todo_app
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  table_calendar: ^3.1.1
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  equatable: ^2.0.5
  image_picker: ^1.1.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  
  
  

